version: '3.9'
services:
  arango:
    build:
      context: .
      dockerfile: arango.Dockerfile
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
      - ARANGO_NO_AUTH=1
      #User root
    volumes:
      - ./data:/var/lib/arangodb3
  grafana:
    # image: grafana/grafana-oss
    build:
      context: .
      dockerfile: grafana.Dockerfile
    ports:
      - 3000:3000 
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource